### ISSUE TITLE
terminate called after throwing an instance of 'GenICam_3_0_Basler_pylon_v5_0::TimeoutException'

### ISSUE THREAD

**Issue by muhkoch** [mabl/PyPylon#10]
Is there any limitation in Exposure Time?

I'm using PyPylon on a Raspberry Pi 3 with an acA2040-25gm and Python 2.7.9. It works very well. Except it drops an error when I like to increase the Exposure Time more than 4377970 us. I'ts arround this value, it changes, sometimes I can go some us more, sometimes a few less.

There are two possibilities to of setting the Exposure time. Either "ExposureTimeAbs" or "ExposureTimeRaw". Both of them drop the same error message if I increase the Value over (arround) 4377970 us. 

The Error Message: 
terminate called after throwing an instance of 'GenICam_3_0_Basler_pylon_v5_0::TimeoutException'

It seams to be a similar error Message as the one form "ragundez". But he hasn't had a problem with the Exposure Time and he hasn't written his solution.

Thank you very much for your help!

**Comment by mabl** [comment]
Hi @muhkoch, can you provide me with a full stack trace of the error?

**Comment by mabl** [comment]
Ah, and you should always be able to increase the image grab timeout: 

```
grab_images(int nr_images, unsigned int timeout=5000)
```
