### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by mmolero** [mabl/PyPylon#11]
I'm trying to compile this package on Windows, However, I was not able to do it. I have used WinPython 3.4 witch its bundled gcc compiler but without success. What is the enviroment you are using to compile it on Windows, Thanks for sharing!!!!

**Comment by mabl** [comment]
Hi @mmolero, you will need a matching compiler to your Python distribution. For Python3.5 its the latest Visual Studio. For 3.4 its a bit more complicated. Please read more information her:
https://blogs.msdn.microsoft.com/pythonengineering/2016/04/11/unable-to-find-vcvarsall-bat/

**Comment by mmolero** [comment]
Thanks, 
Have you tried to compile it using Python 2.7?

**Comment by mabl** [comment]
Yes on Linux. I think there are Windows users also. For 2.7, Microsoft also supplies a standalone compiler installer somewhere.

**Comment by mmolero** [comment]
Thanks,
Now it works using Python 3.5 and compile it using Visual Studio 2015.
