### ISSUE TITLE
Building a .exe application with Pyinstaller

### ISSUE THREAD

**Issue by AkhilAKrasH** [mabl/PyPylon#27]
I'm trying to build a .exe application to easily operate the camera with different (came OS) computers without installing all Python suite.

I have Python 3.5 and I had no problems with my Mono Basler camera (apart of the known problem with managing the buffer). However, when building the .exe Pypylon seems not to work at all. I have read in forums that it could be a problem with the imports done by Cython, but in this field I really do not know how can I get that information.

Have any of you tried this? Do you know which are the files, modules, I need to add to the build with Pyinstaller?

Thanks

**Comment by AkhilAKrasH** [comment]
I found the problem: apart from the .dlls that the code automatically includes from the Basler runtime drivers, there is an additional list of files that have to be added in the folder where the .exe is located in order to run properly. 

You can find this list in the Pylon Deployment Guide, that should be in the Documentation folder from the Basler Pylon viewer suite (normally in C:\Program Files\Basler\pylon 5\Development\Doc) 

Cheers

**Comment by Deathcon5** [comment]
Hey Akhil, I'm having the same issue. I tried the list in the deployment guide, didn't work for me. I'm using the USB3 version of the da1280-um.

**Comment by asegurpe** [comment]
I need this list too, please!!

Thanks a lot.
