### ISSUE TITLE
Pylon version

### ISSUE THREAD

**Issue by robmarkcole** [mabl/PyPylon#34]
Attempting to install on a Windows machine, receiving error 'install with developer options' which indicates I need to install a particular package from https://www.baslerweb.com/en/support/downloads/software-downloads/#type=pylonsoftware;series=baslerbeat but I am unsure which one?
Cheers

**Comment by AkhilAKrasH** [comment]
I installed the Pylon Viewer.

**Comment by robmarkcole** [comment]
OK I just installed the latest version of pylon, and 'Developer' an option during the installation
